### ISSUE TITLE
Support Mapping GCP Secret Name -> Configuration Name

### ISSUE THREAD

**Issue by Cooksauce** [Cultti/Gcp.SecretManager.Provider#2]
Would you be interested accepting a PR to allow some options to map the GCP secret name to dotnet config name.
Something like:
`"my-gcp-secret"` -> `"My:Dotnet:Value"`

This would be helpful in removing the need for the GCP name to match the structure of the project, allow the dotnet app settings to be refactored without affecting the secrets manager, etc.

**Comment by Cultti** [comment]
Interesting idea. So you have an existing GCP secret manager with existing keys that are used by other projects and would like to reuse those secrets?

My plan is to follow as closely as possible with the Azure Key Vault .Net implementation. So for this feature, we would likely implement something similar to `KeyVaultSecretManager` (https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0#use-a-key-name-prefix). For default behavior we would need to move the current behaviour that maps two underscores into a single colon into this manager.

**Comment by Cooksauce** [comment]
> So you have an existing GCP secret manager with existing keys that are used by other projects and would like to reuse those secrets?

Essentially. Or, for various reasons, want to share a GCP secret between projects without coupling their dotnet configuration structure

> So for this feature, we would likely implement something similar to KeyVaultSecretManager

That seems like a good idea to me - looks to be quite extendable.

**Comment by Cultti** [comment]
With version 2.0.0 there is now `ISecretManagerConfigurationLoader` available that you can reimplement however you like. It exposes two methods: `Load` and `GetKey`. `Load` returns true if the key should be loaded and in the default implementation, it returns always true. `GetKey` returns mapped configuration value and in the default loader, it formats those two underscores with a colon.

You can also inherit from the default implementation of the interface named `DefaultSecretManagerConfigurationLoader` in which you may override one of or both those methods. And your implementation can be passed in the options with the `Loader` property.

Let me know if there are any issues and let's look into those :)
